# Generated by Django 3.2.3 on 2021-06-22 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_producto', '0006_auto_20210621_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasFactura',
            fields=[
                ('numero_factura', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Numero Factura')),
                ('fecha_factura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Factura')),
                ('estado_pago_factura', models.CharField(max_length=2, verbose_name='Estado de Pago Factura')),
                ('monto_neto', models.IntegerField(verbose_name='Valor Neto')),
                ('monto_iva', models.FloatField(verbose_name='IVA')),
                ('monto_total', models.IntegerField(verbose_name='Valor Total')),
                ('detalle_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_producto.producto')),
            ],
            options={
                'ordering': ['numero_factura'],
            },
        ),
        migrations.CreateModel(
            name='VentasBoleta',
            fields=[
                ('numero_boleta', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Numero Boleta')),
                ('fecha_boleta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Boleta')),
                ('estado_pago_boleta', models.CharField(max_length=2, verbose_name='Estado de Pago Boleta')),
                ('monto_boleta', models.IntegerField(verbose_name='Valor Total')),
                ('detalle_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_producto.producto')),
            ],
            options={
                'ordering': ['numero_boleta'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalVentasFactura',
            fields=[
                ('numero_factura', models.IntegerField(auto_created=True, db_index=True, verbose_name='Numero Factura')),
                ('fecha_factura', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Factura')),
                ('estado_pago_factura', models.CharField(max_length=2, verbose_name='Estado de Pago Factura')),
                ('monto_neto', models.IntegerField(verbose_name='Valor Neto')),
                ('monto_iva', models.FloatField(verbose_name='IVA')),
                ('monto_total', models.IntegerField(verbose_name='Valor Total')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('detalle_factura', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_producto.producto')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ventas factura',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVentasBoleta',
            fields=[
                ('numero_boleta', models.IntegerField(auto_created=True, db_index=True, verbose_name='Numero Boleta')),
                ('fecha_boleta', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Boleta')),
                ('estado_pago_boleta', models.CharField(max_length=2, verbose_name='Estado de Pago Boleta')),
                ('monto_boleta', models.IntegerField(verbose_name='Valor Total')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('detalle_boleta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_producto.producto')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ventas boleta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
