# Generated by Django 3.2.3 on 2021-06-04 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='SKU')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('modelo_producto', models.CharField(max_length=50, verbose_name='Modelo Producto')),
                ('marca_producto', models.CharField(max_length=50, verbose_name='Marca Producto')),
                ('caract_producto', models.TextField(verbose_name='Caracteristicas Producto')),
                ('catalogo_producto', models.CharField(max_length=50, verbose_name='Catalogo Producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Producto/', verbose_name='Imagen de Producto')),
                ('precio_producto', models.IntegerField(verbose_name='Precio Producto')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalProducto',
            fields=[
                ('sku', models.CharField(db_index=True, max_length=6, verbose_name='SKU')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('modelo_producto', models.CharField(max_length=50, verbose_name='Modelo Producto')),
                ('marca_producto', models.CharField(max_length=50, verbose_name='Marca Producto')),
                ('caract_producto', models.TextField(verbose_name='Caracteristicas Producto')),
                ('catalogo_producto', models.CharField(max_length=50, verbose_name='Catalogo Producto')),
                ('imagen', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen de Producto')),
                ('precio_producto', models.IntegerField(verbose_name='Precio Producto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical producto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
