# Generated by Django 3.2.3 on 2021-06-25 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_catalogo', models.CharField(max_length=50, null=True)),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('feature', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Catalogos',
                'db_table': 'catalogo',
                'ordering': ['nombre_catalogo'],
            },
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock Productos',
                'db_table': 'stock',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='SKU')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('modelo_producto', models.CharField(max_length=50, verbose_name='Modelo Producto')),
                ('marca_producto', models.CharField(max_length=50, verbose_name='Marca Producto')),
                ('caract_producto', models.TextField(verbose_name='Caracteristicas Producto')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='Imagen_Producto/', verbose_name='Imagen de Producto')),
                ('precio_producto', models.IntegerField(verbose_name='Precio Producto')),
                ('id_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_producto.catalogo')),
                ('id_stockproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_producto.stockproducto')),
            ],
            options={
                'ordering': ['sku', 'nombre_producto'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStockProducto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Stock',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProducto',
            fields=[
                ('sku', models.IntegerField(db_index=True, verbose_name='SKU')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('modelo_producto', models.CharField(max_length=50, verbose_name='Modelo Producto')),
                ('marca_producto', models.CharField(max_length=50, verbose_name='Marca Producto')),
                ('caract_producto', models.TextField(verbose_name='Caracteristicas Producto')),
                ('imagen', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen de Producto')),
                ('precio_producto', models.IntegerField(verbose_name='Precio Producto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_catalogo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_producto.catalogo')),
                ('id_stockproducto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_producto.stockproducto')),
            ],
            options={
                'verbose_name': 'historical producto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCatalogo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre_catalogo', models.CharField(max_length=50, null=True)),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('feature', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Catalogo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
