# Generated by Django 3.2.3 on 2021-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['sku']},
        ),
        migrations.RemoveField(
            model_name='historicalproducto',
            name='id_stockproducto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_stockproducto',
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='stockproducto',
            field=models.IntegerField(default=True, verbose_name='Stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stockproducto',
            field=models.IntegerField(default=1, verbose_name='Stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='precio_producto',
            field=models.IntegerField(null=True, verbose_name='Precio Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.IntegerField(null=True, verbose_name='Precio Producto'),
        ),
        migrations.DeleteModel(
            name='HistoricalStockProducto',
        ),
        migrations.DeleteModel(
            name='StockProducto',
        ),
    ]
