# Generated by Django 3.2.3 on 2021-06-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_producto', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='sku',
            field=models.IntegerField(db_index=True, max_length=4, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.IntegerField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='SKU'),
        ),
    ]
