# Generated by Django 3.2.3 on 2021-06-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_producto', '0002_auto_20210626_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='precio_producto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio Producto'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='stockproducto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stockproducto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock'),
        ),
    ]
