# Generated by Django 3.2.3 on 2021-06-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_producto', '0003_auto_20210603_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='sku',
            field=models.IntegerField(db_index=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='SKU'),
        ),
    ]
