# Generated by Django 3.2.3 on 2021-06-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_producto', '0004_auto_20210626_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducto',
            name='id_catalogo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_catalogo',
        ),
        migrations.AddField(
            model_name='producto',
            name='id_catalogo',
            field=models.ManyToManyField(to='api_producto.Catalogo'),
        ),
    ]
