# Generated by Django 3.2.3 on 2021-06-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_producto', '0004_auto_20210603_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['catalogo_producto', 'nombre_producto']},
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='Imagen_Producto/', verbose_name='Imagen de Producto'),
        ),
    ]
