# Generated by Django 3.2.3 on 2021-06-26 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_producto', '0005_auto_20210626_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('SKU', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='sku')),
                ('NombreProducto', models.CharField(max_length=50, null=True, verbose_name='Nombre Producto')),
                ('ModeloProducto', models.CharField(max_length=50, null=True, verbose_name='Modelo Producto')),
                ('MarcaProducto', models.CharField(max_length=50, null=True, verbose_name='Marca Producto')),
                ('Descripcion', models.CharField(max_length=300, null=True, verbose_name='Descripcion Producto')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='Imagen_Producto/', verbose_name='Imagen de Producto')),
                ('StockProducto', models.CharField(max_length=50, null=True, verbose_name='Stock Producto')),
                ('ValorProducto', models.IntegerField(verbose_name='Valor Producto')),
                ('id_catalogo', models.ManyToManyField(to='api_producto.Catalogo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': ['SKU'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductos',
            fields=[
                ('SKU', models.IntegerField(db_index=True, verbose_name='sku')),
                ('NombreProducto', models.CharField(max_length=50, null=True, verbose_name='Nombre Producto')),
                ('ModeloProducto', models.CharField(max_length=50, null=True, verbose_name='Modelo Producto')),
                ('MarcaProducto', models.CharField(max_length=50, null=True, verbose_name='Marca Producto')),
                ('Descripcion', models.CharField(max_length=300, null=True, verbose_name='Descripcion Producto')),
                ('imagen', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen de Producto')),
                ('StockProducto', models.CharField(max_length=50, null=True, verbose_name='Stock Producto')),
                ('ValorProducto', models.IntegerField(verbose_name='Valor Producto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Producto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
