# Generated by Django 3.2.3 on 2021-06-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_producto', '0009_auto_20210626_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcatalogo',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='historicalproductos',
            name='Catalogo',
            field=models.CharField(choices=[('Guitarras Acusticas', 'Guitarras Acusticas'), ('Guitarras Electricas', 'Guitarras Electricas'), ('Bajos Cuatro Cuerdas', 'Bajos Cuatro Cuerdas'), ('Bajos Cinco Cuerdas', 'Bajos Cinco Cuerdas'), ('Bajos Activos', 'Bajos Activos'), ('Bajos Pasivos', 'Bajos Pasivos'), ('Piano Media Cola', 'Piano Media Cola'), ('PianoCola Entera', 'PianoCola Entera'), ('Pianolas', 'Pianolas'), ('Baterias Acusticas', 'Baterias Acusticas'), ('Baterias Electricas', 'Baterias Electricas'), ('Pianolas', 'Pianolas'), ('Cabezales', 'Cabezales'), ('Cajas', 'Cajas')], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproductos',
            name='NombreProducto',
            field=models.CharField(help_text='aqui va el nombre', max_length=50, null=True, verbose_name='Nombre Producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Catalogo',
            field=models.CharField(choices=[('Guitarras Acusticas', 'Guitarras Acusticas'), ('Guitarras Electricas', 'Guitarras Electricas'), ('Bajos Cuatro Cuerdas', 'Bajos Cuatro Cuerdas'), ('Bajos Cinco Cuerdas', 'Bajos Cinco Cuerdas'), ('Bajos Activos', 'Bajos Activos'), ('Bajos Pasivos', 'Bajos Pasivos'), ('Piano Media Cola', 'Piano Media Cola'), ('PianoCola Entera', 'PianoCola Entera'), ('Pianolas', 'Pianolas'), ('Baterias Acusticas', 'Baterias Acusticas'), ('Baterias Electricas', 'Baterias Electricas'), ('Pianolas', 'Pianolas'), ('Cabezales', 'Cabezales'), ('Cajas', 'Cajas')], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='NombreProducto',
            field=models.CharField(help_text='aqui va el nombre', max_length=50, null=True, verbose_name='Nombre Producto'),
        ),
        migrations.DeleteModel(
            name='Catalogo',
        ),
        migrations.DeleteModel(
            name='HistoricalCatalogo',
        ),
    ]
