# Generated by Django 3.2.3 on 2021-06-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_producto', '0010_auto_20210626_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductos',
            name='Descripcion',
            field=models.TextField(max_length=300, null=True, verbose_name='Descripcion Producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Descripcion',
            field=models.TextField(max_length=300, null=True, verbose_name='Descripcion Producto'),
        ),
    ]
