# Generated by Django 3.2.3 on 2021-06-25 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_producto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteCompra',
            fields=[
                ('numero_pedido', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Numero Pedido')),
                ('fecha_pago', models.DateTimeField(verbose_name='Fecha Boleta')),
                ('url_pagina_web', models.CharField(max_length=300, verbose_name='URL Pagina Web')),
                ('codigo_autorizacion', models.IntegerField(verbose_name='Codigo de Autorizacion')),
                ('tipo_transaccion', models.CharField(max_length=50, verbose_name='Tipo Transaccion')),
                ('numero_tarjeta', models.CharField(max_length=16, verbose_name='Estado de Pago Boleta')),
                ('tipo_pago', models.CharField(max_length=25, verbose_name='Tipo de Pago')),
                ('tipo_cuotas', models.CharField(max_length=25, verbose_name='Tipo de Cuotas')),
                ('cantidad_cuotas', models.CharField(max_length=25, verbose_name='Cantidad de Cuotas')),
                ('monto_total_pesos', models.IntegerField(verbose_name='Monto Total')),
            ],
            options={
                'ordering': ['numero_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('numero_venta', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Numero Pedido')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Boleta')),
                ('numero_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_boleta.comprobantecompra')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_producto.producto')),
            ],
            options={
                'ordering': ['numero_venta'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalVentas',
            fields=[
                ('numero_venta', models.IntegerField(db_index=True, verbose_name='Numero Pedido')),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Boleta')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('numero_pedido', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_boleta.comprobantecompra')),
                ('sku', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_producto.producto')),
            ],
            options={
                'verbose_name': 'historical ventas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalComprobanteCompra',
            fields=[
                ('numero_pedido', models.IntegerField(db_index=True, verbose_name='Numero Pedido')),
                ('fecha_pago', models.DateTimeField(verbose_name='Fecha Boleta')),
                ('url_pagina_web', models.CharField(max_length=300, verbose_name='URL Pagina Web')),
                ('codigo_autorizacion', models.IntegerField(verbose_name='Codigo de Autorizacion')),
                ('tipo_transaccion', models.CharField(max_length=50, verbose_name='Tipo Transaccion')),
                ('numero_tarjeta', models.CharField(max_length=16, verbose_name='Estado de Pago Boleta')),
                ('tipo_pago', models.CharField(max_length=25, verbose_name='Tipo de Pago')),
                ('tipo_cuotas', models.CharField(max_length=25, verbose_name='Tipo de Cuotas')),
                ('cantidad_cuotas', models.CharField(max_length=25, verbose_name='Cantidad de Cuotas')),
                ('monto_total_pesos', models.IntegerField(verbose_name='Monto Total')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical comprobante compra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
