# Generated by Django 3.2.3 on 2021-06-26 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_producto', '0006_historicalproductos_productos'),
        ('api_boleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalventas',
            name='sku',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api_producto.productos'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_producto.productos'),
        ),
    ]
